// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmSeverityChange();
void onHumidChange();
void onRandomTemperatureChange();
void onTempChange();
void onAlarmTriggeredChange();

float alarm_severity;
float humid;
float randomTemperature;
float temp;
bool alarm_triggered;

void initProperties(){

  ArduinoCloud.addProperty(alarm_severity, READWRITE, ON_CHANGE, onAlarmSeverityChange);
  ArduinoCloud.addProperty(humid, READWRITE, ON_CHANGE, onHumidChange);
  ArduinoCloud.addProperty(randomTemperature, READWRITE, ON_CHANGE, onRandomTemperatureChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(alarm_triggered, READWRITE, ON_CHANGE, onAlarmTriggeredChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
