// // Code generated by Arduino IoT Cloud, DO NOT EDIT.

// #include <ArduinoIoTCloud.h>
// #include <Arduino_ConnectionHandler.h>

// const char SSID[]     = SECRET_SSID;    // Network SSID (name)
// const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

// void onHumidChange();
// void onTempChange();

// float humid;
// float temp;

// void initProperties(){

//   ArduinoCloud.addProperty(humid, READWRITE, ON_CHANGE, onHumidChange);
//   ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

// }

// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


#include <ArduinoIoTCloud.h>  // LIBRARY NEEDS TO BE INSTALLED
#include <Arduino_ConnectionHandler.h>  // LIBRARY NEEDS TO BE INSTALLED
// Additional LIBRARY: ArduinoHttpClient
#include "arduino_secrets.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRandomTemperatureChange();

float randomTemperature;

void initProperties(){
  ArduinoCloud.addProperty(randomTemperature, READWRITE, ON_CHANGE, onRandomTemperatureChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
